### ISSUE TITLE
Unable to load correct single post

### ISSUE THREAD

**Issue by billrobbins** [braginteractive/ngWP#1]
Thank you for creating this project.  It's been fascinating to learn from.

I've run into a small problem with the single post view.  When I use the content from the project's demo at http://braginteractive.com/demo/wp-json/wp/v2/ the single view of the posts load correctly.  However I've been unable to get the correct single post view to load from other sources.  The most recently published post is the one that displays regardless of which post in the list is clicked.  I've used both sites that I manage and other ones like WP Tavern (https://wptavern.com/wp-json/wp/v2/).

Any thoughts on what might be up there?  Thanks!

**Comment by braginteractive** [comment]
I havent worked with project in a year or so so there might be some changes with the API.

**Comment by billrobbins** [comment]
Gotcha.  I'll look into it.  Thanks
